/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2024-07-25 06:00:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.IsDAO;
import java.util.ArrayList;

public final class input_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("dao.IsDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/master/header.jsp", out, false);
      out.write("\r\n");
      out.write("<section>\r\n");
      out.write("\t<div class=\"content\">\r\n");
      out.write("\t\t<p class=\"title\">타자 성적 등록</p>\r\n");
      out.write("\t\t<form action=\"inputProc.jsp\" name=\"frm\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>타자 선택</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"registration_code\" id=\"registration_code\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"0\">-----타자 선택-----</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"A001\">김길동</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"A002\">이길동</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"A003\">홍길동</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"A004\">조길동</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\">공격 포인트</td>\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>게임 수</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"number\" id=\"game_numbers\" name=\"game_numbers\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>타석 수</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"number\" id=\"appearance\" name=\"appearance\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>안타 수</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"number\" id=\"hit_numbers\" name=\"hit_numbers\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>홈런 수</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"number\" id=\"home_runs\" name=\"home_runs\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\">수비 포인트</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>아웃 카운트 수</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"number\" id=\"put_out\" name=\"put_out\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>더블 플레이 수</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"number\" id=\"double_play\" name=\"double_play\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>에러</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"number\" id=\"error_count\" name=\"error_count\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"등록\" onclick=\"return check()\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"reset\" value=\"다시 쓰기\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction check(){\r\n");
      out.write("\t\tif(document.querySelector(\"#registration_code\").value == \"0\"){\r\n");
      out.write("\t\t\talert(\"타자가 선택되지 않았습니다.\");\r\n");
      out.write("\t\t\tdocument.querySelector(\"#registration_code\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.querySelector(\"#game_numbers\").value.trim()length == 0){\r\n");
      out.write("\t\t\talert(\"게임 수가 입력되지 않았습니다\");\r\n");
      out.write("\t\t\tdocument.querySelector(\"#game_numbers\").value=\"\";\r\n");
      out.write("\t\t\tdocument.querySelector(\"#game_numbers\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.querySelector(\"#appearance\").value.trim()length == 0){\r\n");
      out.write("\t\t\talert(\"타석 수가 입력되지 않았습니다.\");\r\n");
      out.write("\t\t\tdocument.querySelector(\"#appearance\").value=\"\";\r\n");
      out.write("\t\t\tdocument.querySelector(\"#appearance\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.querySelector(\"#hit_numbers\").value.trim()length == 0){\r\n");
      out.write("\t\t\talert(\"안타 수가 입력되지 않았습니다.\");\r\n");
      out.write("\t\t\tdocument.querySelector(\"#hit_numbers\").value=\"\";\r\n");
      out.write("\t\t\tdocument.querySelector(\"#hit_numbers\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.querySelector(\"#home_runs\").value.trim()length == 0){\r\n");
      out.write("\t\t\talert(\"홈런 수가 입력되지 않았습니다.\");\r\n");
      out.write("\t\t\tdocument.querySelector(\"#home_runs\").value=\"\";\r\n");
      out.write("\t\t\tdocument.querySelector(\"#home_runs\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.querySelector(\"#put_out\").value.trim()length == 0){\r\n");
      out.write("\t\t\talert(\"아웃 카운트 수가 입력되지 않았습니다.\");\r\n");
      out.write("\t\t\tdocument.querySelector(\"#put_out\").value=\"\";\r\n");
      out.write("\t\t\tdocument.querySelector(\"#put_out\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.querySelector(\"#double_play\").value.trim()length == 0){\r\n");
      out.write("\t\t\talert(\"더블 플레이 수가 입력되지 않았습니다.\");\r\n");
      out.write("\t\t\tdocument.querySelector(\"#double_play\").value=\"\";\r\n");
      out.write("\t\t\tdocument.querySelector(\"#double_play\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.querySelector(\"#error_count\").value.trim()length == 0){\r\n");
      out.write("\t\t\talert(\"에러 수가 입력되지 않았습니다.\");\r\n");
      out.write("\t\t\tdocument.querySelector(\"#error_count\").value=\"\";\r\n");
      out.write("\t\t\tdocument.querySelector(\"#error_count\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/master/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
